Update minimum msrestazure package to 0.4.9
The Azure SDK for Python, 2.0.0rc6, has an implicit dependency on
python module requests 2.8.0+.

The msrestazure module 0.4.9 changes its dependency on msrest from
0.4.4 to 0.4.10; however, the Azure SDK for Python defines its
minimum version of msrestazure as 0.4.0.

Further, version 0.4.8 of the msrest module changes its minimum
version requirement of requests from 2.7.0 to 2.14.1.

If one uses the request module prior to 2.8.0 then they are likely
to see this exception:
SysCallError: (32, 'EPIPE')

The exception can be triggered by doing the following:

Use the Azure SDK to store a copy of the compute and network clients
Create a VM
Create a NIC
Deallocate VM and attach NIC to VM
Start VM
The next use of the compute or network clients will trigger a
SysCallError: (32, 'EPIPE') error.
The EPIPE error is gracefully handled by the requests module in 2.8.0.

Without this change, any user on a system that is running an older
version of requests and installs the 2.0.0rc6 Azure SDK via pip
will encounter this issue because the minimum dependencies will be
satisfied and requests will not be upgraded.

This change is to mitigate issues with uncaught exceptions from
an older requests module when the Azure SDK is not using a
virtualenv deployment.