The goal of this commit is to fix an issue occuring while using the azure cognitive services and especially the face API. The bug occurs when trying to add a face to a large face group while using the add_face_from_url method from the FaceClient in azure.cognitiveservices.vision.face and specifying the target_face optional parameter. The bug that occurs is that when trying to serialize the list of integers it raises a TypeError with the message:   "sequence item 0: expected str instance, int found" Here is the complete stack trace:    Traceback (most recent call last):      File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 708, in serialize_data        data, data_type[1:-1], **kwargs)      File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 789, in serialize_iter        serialized = div.join(serialized)    TypeError: sequence item 0: expected str instance, int found
   During handling of the above exception, another exception occurred:

   Traceback (most recent call last):
     File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 622, in query
       output = self.serialize_data(data, data_type, **kwargs)
     File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 713, in serialize_data
       SerializationError, msg.format(data, data_type), err)
     File "/usr/local/lib/python3.6/site-packages/msrest/exceptions.py", line 51, in raise_with_traceback
       raise error.with_traceback(exc_traceback)
     File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 708, in serialize_data
       data, data_type[1:-1], **kwargs)
     File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 789, in serialize_iter
       serialized = div.join(serialized)
   msrest.exceptions.SerializationError: Unable to serialize value: [588, 221, 482, 482] as type: '[int]'., TypeError: sequence item 0: expected str instance, int found

   During handling of the above exception, another exception occurred:

   Traceback (most recent call last):
     File "fail_example.py", line 87, in <module>
       target_face=face_rectangle
     File "/usr/local/lib/python3.6/site-packages/azure/cognitiveservices/vision/face/operations/large_face_list_operations.py", line 614, in add_face_from_url
       query_parameters['targetFace'] = self._serialize.query("target_face", target_face, '[int]', div=',')
     File "/usr/local/lib/python3.6/site-packages/msrest/serialization.py", line 630, in query
       raise TypeError("{} must be type {}.".format(name, data_type))
   TypeError: target_face must be type [int].

The solution I provide to the issue is that in the method add_face_from_url
of the FaceClient I serialize the target_face to an list of string instead of
a list of int. Doing this solves the issue.