Remove non-existing instrumentor (#42202)
When running one of the Azure AI Projects samples that uses OTel tracing, I saw the below error in the console. Removing this old instrumentor, as it no longer exists (it existed in older preview versions of azure-ai-projects package, before Agents was split to its own package azure-ai-agents).

Failed to import AIAgentsInstrumentor from azure.ai.projects.telemetry.agents
Traceback (most recent call last):
  File "C:\Users\dcohen\AppData\Local\Programs\Python\Python312\Lib\site-packages\azure\monitor\opentelemetry\_configure.py", line 332, in _setup_additional_azure_sdk_instrumentations
    module = __import__(module_path, fromlist=[class_name])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'azure.ai.projects.telemetry'