Deid GA release (#40850)
* Regenerated for stable API version

* Custom methods

* Customization WIP

* Add client methods

* Overrides for async client

* Update tests for new API spec

* AttributeError: 'DeidentificationClient' object has no attribute 'begin_deidentify_documents'

* Internal operations!

* Still missing client method

* Update tests for job refactor

* Inheritance for customizations

* Model imports

* Add kwargs for maxpagesize

* Add @distributed_trace

* Fix pylint-next errors/warnings

* Update configuration files

* Changelog update

* Updating tests for new API version

* Pagination test, fixes for urls

* work in progress test sanitizing

* Regenerated for stable API version

* Custom methods

* Customization WIP

* Add client methods

* Overrides for async client

* Update tests for new API spec

* AttributeError: 'DeidentificationClient' object has no attribute 'begin_deidentify_documents'

* Internal operations!

* Still missing client method

* Update tests for job refactor

* Inheritance for customizations

* Model imports

* Add kwargs for maxpagesize

* Add @distributed_trace

* Fix pylint-next errors/warnings

* Update configuration files

* Changelog update

* Updating tests for new API version

* Pagination test, fixes for urls

* work in progress test sanitizing

* Tests running against latest TypeSpec

* Update TypeSpec before customizations

* Pull in SDK client name updates

* Update changelog and samples

* update changelog to unreleased

* remove unreleased beta version from changelog

* Updating version to 1.0.0

* Update README, samples

* Update spelling

* Separate samples for each operation

* adding black formatting

* update snippets after black formatting

* Update generated code

* Updating TypeSpec commit

---------

Co-authored-by: Alexa Thomases <athomases@microsoft.com>
Co-authored-by: Mike Soennichsen <msoennichsen@microsoft.com>
Co-authored-by: Josiah Vinson <jovinson@microsoft.com>