Without subnet it is impossible to create a Network Interface
When try use without this commit, I receive error from azure api server:
```
....
  File "/Library/Python/2.7/site-packages/msrestazure/azure_operation.py", line 629, in result
    raise self._exception
msrestazure.azure_exceptions.CloudError: Subnet reference is required for ipconfiguration /subscriptions/49d0145c-3194-47eb-81d8-0845a97f3377/resourceGroups/jEugene-je/providers/Microsoft.Network/networkInterfaces/jEugene-je/ipConfigurations/default.
```